C:/sqlite/sqlite3.exe AuctionBase < create.sql
C:/sqlite/sqlite3.exe AuctionBase < load.txt
C:/sqlite/sqlite3.exe AuctionBase < constraints_verify.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger1_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger2_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger3_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger4_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger5_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger6_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger7_add.sql
C:/sqlite/sqlite3.exe AuctionBase < trigger8_add.sql